# Generated by Django 5.2.17 on 2026-08-22 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alertsubscription_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisasterEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('disaster_type', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=160)),
                ('state', models.CharField(blank=True, max_length=120)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('rainfall_mm', models.FloatField(default=0)),
                ('temperature_c', models.FloatField(default=0)),
                ('humidity_pct', models.FloatField(default=0)),
                ('wind_speed_kmh', models.FloatField(default=0)),
                ('magnitude', models.FloatField(default=0)),
                ('affected_population', models.PositiveIntegerField(default=0)),
                ('severity', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('district', models.CharField(max_length=160)),
                ('state', models.CharField(blank=True, max_length=120)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('emergency_available', models.BooleanField(default=True)),
                ('contact', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Shelter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('district', models.CharField(max_length=160)),
                ('state', models.CharField(blank=True, max_length=120)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('capacity', models.PositiveIntegerField(default=0)),
                ('contact', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.RenameIndex(
            model_name='alertsubscription',
            new_name='core_alerts_email_58b28c_idx',
            old_name='core_alertsu_email_9bdb4e_idx',
        ),
        migrations.AddIndex(
            model_name='disasterevent',
            index=models.Index(fields=['disaster_type', 'district'], name='core_disast_disaste_b6f250_idx'),
        ),
        migrations.AddIndex(
            model_name='disasterevent',
            index=models.Index(fields=['date'], name='core_disast_date_dd49ec_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='hospital',
            unique_together={('name', 'district')},
        ),
        migrations.AlterUniqueTogether(
            name='shelter',
            unique_together={('name', 'district')},
        ),
    ]
